### ISSUE TITLE
Sync rating with server

### ISSUE THREAD

**Issue by Mattie432** [patzm/plex-music-rating-sync#1]
Hi, thanks for the project. Helped me get started with coding an iTunes. xml library -> plex syncer. Noticed you had a comment on current issues **How to change the ratings on the server (API endpoint)**.

In order to set rating on the server side you need to use the [edit function](http://python-plexapi.readthedocs.io/en/latest/modules/base.html#plexapi.base.PlexPartialObject.edit) and pass a dict of values to change.

e.g.
```
def updateTrack( artist, track, rating ):
    music = plex.library.section('Music')
    foundArtist = music.searchArtists(**{'title': artist})[0]
    foundTrack = foundArtist.track(track)
    print("Rating before: ", foundTrack._data.attrib.get('userRating'))
    foundTrack.edit(**{'userRating.value': rating})
    print("Rating after: ", foundTrack._data.attrib['userRating'])

updateTrack('30 Seconds To Mars', 'A Beautiful Lie', 6)
```

**Comment by patzm** [comment]
Hi Matthew,
thanks for the suggestion!!! I somehow overlooked this in hindsight pretty oviously named method 😄 . I implemented a first working version now with commit 84a3e86a21b79ac923ef47178afae1774991b93c .

Regarding your goal of writing an iTunes parser: have you thought about using the iTunes COM interface instead of directly reading the xml? I stumbled across [this documentation](http://www.joshkunz.com/iTunesControl/). Maybe you are motivate to collaborate here in this repo? Then we can share a lot of common code.
